select
	cont_id
	, CONT_ID
	, cont_title
	, CONT_CONTENT
	, (SELECT USER_NAME FROM TB_USER_INFO B
		WHERE A.USER_PID = B.USER_PID) USER_NAME
	, (SELECT COUNT(1) FROM TB_CONT_READ_CNT B
		WHERE A.CONT_ID = B.CONT_ID) READ_CNT
from TB_CONT_REVIEW A
where delete_yn is null
ORDER BY 1
;

SELECT * FROM TB_USER_INFO

;
INSERT INTO TB_CONT_READ_CNT
	(SEQ_NUM, CONT_ID, USER_PID, READ_DT)
VALUES (MAX(SELECT SEQ_NUM FROM TB_CONT_READ_CNT), #cont_id#, #user_pid#, SYSDATE)
;
INSERT INTO TB_CONT_READ_CNT
	(SEQ_NUM, CONT_ID, USER_PID, READ_DT)
VALUES ((SELECT MAX(NVL(SEQ_NUM, 0)) FROM TB_CONT_READ_CNT), 'RV0001', 'ID0001', SYSDATE)
